### ISSUE TITLE
Transfer to OME org, publish to GitHub

### ISSUE THREAD

**Issue by manics** [manics/action-major-minor-tag-calculator#39]
https://github.com/ome/omero-server-docker/pull/51#issuecomment-774017960

@jburel I've just tagged `v1.0.0` and created a GitHub release. Do you want to transfer this to the ome org now and keep me as an admin?

In addition it would be nice to publish this to the GitHub marketplace:
https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action
but an organisation admin will have to agree to the terms and conditions.

**Comment by manics** [comment]
@jburel Are you still planning to move this to the ome org? I'd like to make use of this action, so having it in it's final home would be great!

**Comment by jburel** [comment]
@manics sorry I had many things to do and forgot about that one. I will take of that.

**Comment by manics** [comment]
@jburel I'm using this in a JupyterHub repo, so to make things easier I'll move it to that github org instead. The other advantage is OME won't need to sign the GitHub actions agtreement to publish it which opefully makes things slightly easier for you.

**Comment by jburel** [comment]
sorry @manics I completely forgot about it since I put some of the work onhold due to other deadlines
Could you point me to the new repo?
I made few changes at the time on my branch, if they are not included I will submit them

**Comment by manics** [comment]
https://github.com/jupyterhub/action-major-minor-tag-calculator

**Comment by jburel** [comment]
thanks
